// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Episode() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<article aria-labelledby=\"episode-5-title\" class=\"py-10 sm:py-12\"><div class=\"lg:px-8\"><div class=\"lg:max-w-4xl\"><div class=\"mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0\"><div class=\"flex flex-col items-start\"><h2 id=\"episode-5-title\" class=\"mt-2 text-lg font-bold text-slate-900\"><a href=\"/5\">5: Bill Lumbergh</a></h2><time datetime=\"2022-02-24T00:00:00.000Z\" class=\"order-first font-mono text-sm leading-7 text-slate-500\">February 24, 2022</time><p class=\"mt-1 text-base leading-7 text-slate-700\">He’s going to need you to go ahead and come in on Saturday, but there’s a lot more to the story than you think.</p><div class=\"mt-4 flex items-center gap-4\"><button type=\"button\" aria-label=\"Play episode 5: Bill Lumbergh\" class=\"flex items-center gap-x-3 text-sm font-bold leading-6 text-pink-500 hover:text-pink-700 active:text-pink-900\"><div class=\"svg\"></div><span aria-hidden=\"true\">Listen</span></button> <span aria-hidden=\"true\" class=\"text-sm font-bold text-slate-400\">/</span> <a class=\"flex items-center text-sm font-bold leading-6 text-pink-500 hover:text-pink-700 active:text-pink-900\" aria-label=\"Show notes for episode 5: Bill Lumbergh\" href=\"/5\">Show notes</a></div></div></div></div></div></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
